export ZSH="$HOME/.oh-my-zsh"
plugins=(git docker docker-compose brew)

source $ZSH/oh-my-zsh.sh
source $HOME/Code/macsetup/env/zsh-theme.sh

if [ -x /opt/homebrew/bin/mise ]; then
  eval "$(/opt/homebrew/bin/mise activate zsh)"
fi

path+=("/opt/homebrew/bin")
path+=("$HOME/Code/macsetup/bin")
path+=("$HOME/.local/bin")
alias gpop="git reset HEAD^"
alias gtsync="git fetch --tags && git push origin --tags"
alias yolo="claude --dangerously-skip-permissions"
[[ -f $HOME/Code/macsetup/zshrc-user.sh ]] && source $HOME/Code/macsetup/zshrc-user.sh
